-- Örnek Tarif Verileri Ekle
-- Bu dosyayı Supabase SQL Editor'da çalıştırın

-- Örnek tarifler ekle
INSERT INTO public.recipes (
  id,
  user_id,
  title,
  description,
  ingredients,
  instructions,
  cooking_time,
  difficulty,
  servings,
  image_url,
  is_public,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'Mercimek Çorbası',
  'Geleneksel Türk mutfağının vazgeçilmez lezzeti, kırmızı mercimek çorbası.',
  '["1 su bardağı kırmızı mercimek", "1 adet soğan", "1 adet havuç", "2 yemek kaşığı tereyağı", "6 su bardağı su", "Tuz, karabiber"]',
  '["Mercimekleri yıkayıp süzün.", "Soğanı ve havucu küp küp doğrayın.", "Tereyağında soğanları kavurun.", "Mercimekleri ve suyu ekleyin.", "30 dakika pişirin.", "Blenderdan geçirin."]',
  45,
  'easy',
  4,
  'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'Tavuk Sote',
  'Pratik ve lezzetli tavuk sote tarifi.',
  '["500g tavuk göğsü", "2 adet biber", "1 adet soğan", "3 yemek kaşığı zeytinyağı", "Tuz, karabiber"]',
  '["Tavukları kuşbaşı doğrayın.", "Sebzeleri julyen doğrayın.", "Zeytinyağında tavukları kavurun.", "Sebzeleri ekleyin.", "15 dakika pişirin."]',
  30,
  'medium',
  4,
  'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800',
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'Brownie',
  'Çikolatalı brownie tarifi.',
  '["200g bitter çikolata", "150g tereyağı", "3 adet yumurta", "200g şeker", "100g un"]',
  '["Çikolatayı benmari usulü eritin.", "Tereyağını ekleyip karıştırın.", "Yumurta ve şekeri çırpın.", "Un ekleyip karıştırın.", "180°C fırında 25 dakika pişirin."]',
  45,
  'medium',
  8,
  'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800',
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'Pizza Margherita',
  'Klasik İtalyan pizza tarifi.',
  '["Pizza hamuru", "Domates sosu", "Mozzarella peyniri", "Fesleğen", "Zeytinyağı"]',
  '["Hamuru açın.", "Domates sosunu sürün.", "Mozzarella peynirini ekleyin.", "Fesleğen yapraklarını ekleyin.", "250°C fırında 12-15 dakika pişirin."]',
  30,
  'medium',
  4,
  'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?w=800',
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'Sushi Roll',
  'Ev yapımı sushi roll tarifi.',
  '["Sushi pirinci", "Nori yaprağı", "Somon", "Salatalık", "Avokado"]',
  '["Pirinci pişirin ve soğutun.", "Nori yaprağını yayın.", "Pirinci yayın.", "Balık ve sebzeleri ekleyin.", "Rulo yapın.", "Dilimleyin."]',
  60,
  'hard',
  2,
  'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800',
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'Köfte',
  'Geleneksel Türk köfte tarifi.',
  '["500g kıyma", "1 adet soğan", "2 adet yumurta", "1 su bardağı galeta unu", "Tuz, karabiber, kimyon"]',
  '["Soğanı rendeleyin.", "Tüm malzemeleri karıştırın.", "Köfte şekli verin.", "Tavada veya ızgarada pişirin."]',
  25,
  'easy',
  6,
  'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800',
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'Tiramisu',
  'İtalyan tatlısı tiramisu.',
  '["6 adet yumurta", "500g mascarpone", "200g şeker", "200g lady finger", "Kahve", "Kakao"]',
  '["Yumurta sarılarını çırpın.", "Mascarpone ekleyin.", "Lady fingerları kahveye batırın.", "Katmanları oluşturun.", "Buzdolabında 4 saat bekletin."]',
  30,
  'medium',
  8,
  'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800',
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  (SELECT id FROM auth.users LIMIT 1),
  'Salata',
  'Taze ve sağlıklı salata.',
  '["Marul", "Domates", "Salatalık", "Zeytin", "Zeytinyağı", "Limon"]',
  '["Sebzeleri yıkayın.", "Doğrayın.", "Karıştırın.", "Zeytinyağı ve limon ekleyin."]',
  10,
  'easy',
  4,
  'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
  true,
  NOW(),
  NOW()
); 